geonode/layers/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url
from django.conf import settings
from django.views.generic import TemplateView

js_info_dict = {
    'packages': ('geonode.layers',),
}

urlpatterns = patterns(
    'geonode.layers.views',
    url(r'^$',
        TemplateView.as_view(template_name='layers/layer_list.html'),
        {'facet_type': 'layers', 'is_layer': True},
        name='layer_browse'),
    url(r'^upload$', 'layer_upload', name='layer_upload'),
    url(r'^upload_metadata$', 'layer_metadata_upload', name='layer_metadata_upload'),
    url(r'^upload_style$', 'layer_sld_upload', name='layer_sld_upload'),
    url(r'^load_layer_data$', 'load_layer_data', name='load_layer_data'),
    url(r'^(?P<layername>[^/]*)$', 'layer_detail', name="layer_detail"),
    url(r'^(?P<layername>[^/]*)/metadata$', 'layer_metadata', name="layer_metadata"),
    url(r'^(?P<layername>[^/]*)/metadata_advanced$', 'layer_metadata_advanced', name="layer_metadata_advanced"),
    url(r'^(?P<layername>[^/]*)/remove$', 'layer_remove', name="layer_remove"),
    url(r'^(?P<granule_id>[^/]*)/(?P<layername>[^/]*)/granule_remove$', 'layer_granule_remove',
        name="layer_granule_remove"),
    url(r'^(?P<layername>[^/]*)/replace$', 'layer_replace', name="layer_replace"),
    url(r'^(?P<layername>[^/]*)/thumbnail$', 'layer_thumbnail', name='layer_thumbnail'),
    url(r'^(?P<layername>[^/]*)/get$', 'get_layer', name='get_layer'),
    url(r'^(?P<layername>[^/]*)/metadata_detail$', 'layer_metadata_detail', name='layer_metadata_detail'),
    url(r'^(?P<layername>[^/]*)/metadata_upload$', 'layer_metadata_upload', name='layer_metadata_upload'),
    url(r'^(?P<layername>[^/]*)/style_upload$', 'layer_sld_upload', name='layer_sld_upload'),
    url(r'^(?P<layername>[^/]*)/feature_catalogue$', 'layer_feature_catalogue', name='layer_feature_catalogue'),
    url(r'^metadata/batch/(?P<ids>[^/]*)/$', 'layer_batch_metadata', name='layer_batch_metadata'),

    # url(r'^api/batch_permissions/?$', 'batch_permissions',
    #    name='batch_permssions'),
    # url(r'^api/batch_delete/?$', 'batch_delete', name='batch_delete'),
)

# -- Deprecated url routes for Geoserver authentication -- remove after GeoNode 2.1
# -- Use /gs/acls, gs/resolve_user/, gs/download instead
if 'geonode.geoserver' in settings.INSTALLED_APPS:
    urlpatterns = patterns('geonode.geoserver.views',
                           url(r'^acls/?$', 'layer_acls', name='layer_acls_dep'),
                           url(r'^resolve_user/?$', 'resolve_user', name='layer_resolve_user_dep'),
                           url(r'^download$', 'layer_batch_download', name='layer_batch_download_dep'),
                           ) + urlpatterns

geonode/qgis_server/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url

from geonode.qgis_server.views import (
    download_zip,
    download_qgs,
    download_map,
    tile,
    tile_404,
    legend,
    layer_ogc_request,
    qgis_server_request,
    qgis_server_pdf,
    qgis_server_map_print,
    geotiff,
    download_qlr,
    qml_style, set_thumbnail, default_qml_style)


urlpatterns = patterns(

    # Specific for a QGIS Layer
    '',
    url(
        r'^download-zip/(?P<layername>[\w]*)$',
        download_zip,
        name='download-zip'
    ),
    url(
        r'^download-qgs/(?P<layername>[\w]*)$',
        download_qgs,
        name='download-qgs'
    ),
    url(
        r'^download-map/(?P<mapid>\d+)$',
        download_map,
        name='download-map'
    ),
    url(
        r'^tiles/'
        r'(?P<layername>[^/]*)/'
        r'(?P<z>[0-9]*)/'
        r'(?P<x>[0-9]*)/'
        r'(?P<y>[0-9]*).png$',
        tile,
        name='tile'
    ),
    url(
        r'^tiles/'
        r'(?P<layername>[^/]*)/'
        r'(?P<style>[^/]*)/'
        r'(?P<z>[0-9]*)/'
        r'(?P<x>[0-9]*)/'
        r'(?P<y>[0-9]*).png$',
        tile,
        name='tile'
    ),
    url(
        r'^tiles/'
        r'(?P<layername>[^/]*)/'
        r'(?P<style>[^/]*)/'
        r'\{z\}/\{x\}/\{y\}.png$',
        tile_404,
        name='tile'
    ),
    url(
        r'^tiles/'
        r'(?P<layername>[^/]*)/\{z\}/\{x\}/\{y\}.png$',
        tile_404,
        name='tile'
    ),
    url(
        r'^geotiff/(?P<layername>[\w]*)$',
        geotiff,
        name='geotiff'
    ),
    url(
        r'^legend/(?P<layername>[\w]*)/'
        r'(?P<style>[\w]*)/'
        r'(?:/(?P<layertitle>(True|False)))?$',
        legend,
        name='legend'
    ),
    url(
        r'^legend/(?P<layername>[\w]*)(?:/(?P<layertitle>(True|False)))?$',
        legend,
        name='legend'
    ),
    url(
        r'^ogc/(?P<layername>[\w]+)$',
        layer_ogc_request,
        name='layer-request'
    ),

    # Generic for OGC
    # WMS entry point, this URL is not specific to WMS, you should remove it ?
    url(
        r'^wms/$',
        qgis_server_request,
        name='request'
    ),
    url(
        r'^ogc/$',
        qgis_server_request,
        name='request'
    ),

    # Generic for the app
    url(
        r'^pdf/info\.json$',
        qgis_server_pdf,
        name='pdf'
    ),
    url(
        r'^map/print$',
        qgis_server_map_print,
        name='map-print'
    ),
    url(
        r'^style/default/(?P<layername>[^/]*)(?:/(?P<style_name>[^/]*))?$',
        default_qml_style,
        name='default-qml'
    ),
    url(
        r'^style/upload/(?P<layername>[^/]*)(?:/(?P<style_name>[^/]*))?$',
        qml_style,
        name='upload-qml'
    ),
    url(
        r'^style/remove/(?P<layername>[^/]*)/(?P<style_name>[^/]*)$',
        qml_style,
        name='remove-qml'
    ),
    url(
        r'^style/download/(?P<layername>[^/]*)(?:/(?P<style_name>[^/]*))?$',
        qml_style,
        name='download-qml'
    ),
    url(
        r'^thumbnail/set/(?P<layername>[^/]*)$',
        set_thumbnail,
        name='set-thumbnail'
    ),
    url(
       r'^download-qlr/(?P<layername>[\w]*)$',
       download_qlr,
       name='download-qlr'
    ),
)

geonode/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls

from geonode.api.urls import api
from geonode.api.views import verify_token, roles, users, admin_role

from autocomplete_light.registry import autodiscover

# Setup Django Admin
autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

                       # Static pages
                       url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # data.json
                       url(r'^data.json$', 'geonode.catalogue.views.data_json', name='data_json'),

                       # ident
                       url(r'^ident.json$', 'geonode.views.ident_json', name='ident_json'),

                       # h keywords
                       url(r'^h_keywords_api$', 'geonode.views.h_keywords', name='h_keywords_api'),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       # (r'^comments/', include('dialogos.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),

                       # Accounts
                       url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),
                       url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt'), name='robots'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),
                       (r'^services/', include('geonode.services.urls')),

                       # OAuth Provider
                       url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

                       # Api Views
                       url(r'^api/o/v4/tokeninfo', verify_token, name='tokeninfo'),
                       url(r'^api/roles', roles, name='roles'),
                       url(r'^api/adminRole', admin_role, name='adminRole'),
                       url(r'^api/users', users, name='users'),
                       url(r'', include(api.urls)),
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if "geonode.contrib.metadataxsl" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^showmetadata/', include('geonode.contrib.metadataxsl.urls')),
                            )

if "geonode.contrib.createlayer" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^createlayer/', include('geonode.contrib.createlayer.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    from geonode.geoserver.views import get_capabilities
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            # capabilities
                            url(r'^capabilities/layer/(?P<layerid>\d+)/$',
                                get_capabilities, name='capabilities_layer'),
                            url(r'^capabilities/map/(?P<mapid>\d+)/$',
                                get_capabilities, name='capabilities_map'),
                            url(r'^capabilities/user/(?P<user>[\w.]+)/$',
                                get_capabilities, name='capabilities_user'),
                            url(r'^capabilities/category/(?P<category>\w+)/$',
                                get_capabilities, name='capabilities_category'),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )
if 'geonode.qgis_server' in settings.INSTALLED_APPS:
    # QGIS Server's urls
    urlpatterns += patterns('',
                            (r'^qgis-server/',
                             include(
                                 'geonode.qgis_server.urls',
                                 namespace='qgis_server')), )

if settings.NOTIFICATIONS_MODULE in settings.INSTALLED_APPS:
    notifications_urls = '{}.urls'.format(settings.NOTIFICATIONS_MODULE)
    urlpatterns += patterns('',
                            (r'^notifications/', include(notifications_urls)),
                            )
if "djmp" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^djmp/', include('djmp.urls')),
                            )

if 'geonode.contrib.ows_api' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url('^', include('geonode.contrib.ows_api.urls')),
                            )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.LOCAL_MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

# Featured Maps Pattens
urlpatterns += patterns('',
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/$', 'geonode.maps.views.featured_map'),
                        (r'^featured/(?P<site>[A-Za-z0-9_\-]+)/info$', 'geonode.maps.views.featured_map_info'),
                        )


if settings.MONITORING_ENABLED:
    urlpatterns += [url(r'^monitoring/', include('geonode.contrib.monitoring.urls', namespace='monitoring'))]

geonode/layers/templates/layers/layer_base.html
{% extends "geonode_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}data{% endblock body_class %}

{% block body_outer %}
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/layers/templates/layers/layer_leaflet_map.html
{% load leaflet_tags %}
{% load i18n %}

{% leaflet_js %}
{% leaflet_css %}

<style>
    .leaflet-container { /* all maps */
        height: 400px;
    }
    
    .leaflet-control-zoom, .leaflet-control-zoomslider {  /* all controls */
        position: relative;
        left: 0px !important;
    }
</style>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function (event) {
      L.TileLayer.BetterWMS = L.TileLayer.WMS.extend({

        onAdd: function (map) {
          // Triggered when the layer is added to a map.
          // Register a click listener, then do all the upstream WMS things
          L.TileLayer.WMS.prototype.onAdd.call(this, map);
          map.on('click', this.getFeatureInfo, this);
        },

        onRemove: function (map) {
          // Triggered when the layer is removed from a map.
          // Unregister a click listener, then do all the upstream WMS things
          L.TileLayer.WMS.prototype.onRemove.call(this, map);
          map.off('click', this.getFeatureInfo, this);
        },

        getFeatureInfo: function (evt) {
          // Make an AJAX request to the server and hope for the best
          var url = this.getFeatureInfoUrl(evt.containerPoint),
              showResults = L.Util.bind(this.showGetFeatureInfo, this);
          // console.log(url);
          $.ajax({
            url: url,
            success: function (data, status, xhr) {
              var err = typeof data === 'string' ? null : data;
              showResults(err, evt.latlng, data);
            },
            error: function (xhr, status, error) {
              showResults(error);
            }
          });
        },

        getFeatureInfoUrl: function (layerPoint) {
          // Construct a GetFeatureInfo request URL given a point
          if (!map) {
              map = this._map;
          }
          // Compute WMS options
          var bounds = map.getBounds();
          var size = map.getSize();
          var wmsVersion = parseFloat(this.wmsParams.version);
          var crs = this.options.crs || map.options.crs;
          var projectionKey = wmsVersion >= 1.3 ? 'crs' : 'srs';
          var nw = crs.project(bounds.getNorthWest());
          var se = crs.project(bounds.getSouthEast());

          // Assemble WMS parameter string

          var size = this._map.getSize(),
              params = {
                request: 'GetFeatureInfo',
                service: 'WMS',
                srs: 'EPSG:4326',
                styles: this.wmsParams.styles,
                transparent: this.wmsParams.transparent,
                version: this.wmsParams.version,
                format: this.wmsParams.format,
                // bbox: this._map.getBounds().toBBoxString(),
                height: size.y,
                width: size.x,
                layers: this.wmsParams.layers,
                query_layers: this.wmsParams.layers,
                info_format: 'text/html'
              };
          params[projectionKey] = crs.code;
          params.bbox = (
              wmsVersion >= 1.3 && crs === L.CRS.EPSG4326 ?
              [se.y, nw.x, nw.y, se.x] :
              [nw.x, se.y, se.x, nw.y]
          ).join(',');

          params[params.version === '1.3.0' ? 'i' : 'x'] = Math.floor(layerPoint.x);
          params[params.version === '1.3.0' ? 'j' : 'y'] = Math.floor(layerPoint.y);

          return this._url + L.Util.getParamString(params, this._url, true);
        },

        showGetFeatureInfo: function (err, latlng, content) {
          if (err) { console.log(err); return; } // do nothing if there's an error

          // Otherwise show the content in a popup, or something.
          L.popup({ maxWidth: 900, maxHeight: 200})
            .setLatLng(latlng)
            .setContent(content)
            .openOn(this._map);
        }
      });

        L.tileLayer.betterWms = function (url, options) {
          return new L.TileLayer.BetterWMS(url, options);
        };
        var osm = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        });

        var unesco = L.tileLayer(
            'http://en.unesco.org/tiles/{z}/{x}/{y}.png', {
            attribution: '&copy; unesco'
        });

        var unesco_geodata = L.tileLayer(
            'http://en.unesco.org/tiles/geodata/{z}/{x}/{y}.png', {
            attribution: '&copy; unesco'
        });
		
        var OpenMapSurfer_Roads = L.tileLayer('http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}', {
            maxZoom: 20,
            attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        });

        // not yet available
        // var unesco_white = L.tileLayer(
        //     'http://en.unesco.org/tiles/white/{z}/{x}/{y}.png', {
        //     attribution: '&copy; unesco'
        // });

        var base_maps = {
            "OpenMapSurfer_Roads": OpenMapSurfer_Roads,
            'OpenStreetMap': osm
        };

        var overlay_layer = {};

        var map = L.map('preview_map',{measureControl: true});

      	//add elements to maps page
        var scale_bar = L.control.scale().addTo(map);
       	//var attribution = L.control.attribution({prefix: 'UNESCO-IHP-Wins'}).addTo(map);
      	//on surcharge attribution
      	map.attributionControl.addAttribution('<a href="http://en.unesco.org/themes/water-security/hydrology", class="your_class">UNESCO-IHP-Wins</a>');

        L.Control.Watermark = L.Control.extend({
          onAdd: function(map) {
          var img = L.DomUtil.create('img');

          // Default to Geonode logo
          img.src = '{{ STATIC_URL }}/geonode/img/logo.png';
          img.style.width = '120px';

          return img;
          },

          onRemove: function(map) {
          // Nothing to do here
          }
        });

        L.control.watermark = function(opts) {
          return new L.Control.Watermark(opts);
        };

        L.control.watermark({ position: 'bottomright' }).addTo(map);

        // L.control.measureControl.addTo(map);
        map.addLayer(OpenMapSurfer_Roads);

        {% if layer_bbox %}
            zoom_to_box(map, [{{ layer_bbox }}]);
        {% endif %}

        var tile_layer;
        {% if resource.get_tiles_url %}
            tile_layer = L.tileLayer("{{ resource.get_tiles_url|safe }}",
                    {
                        'opacity': 0.8
                    });
        {%  elif resource.ptype == "gxp_wmscsource"  %}
            tile_layer = L.tileLayer.betterWms('{{ resource.ows_url|safe }}', {
                layers: '{{ resource.alternate }}',
                format: 'image/png',
                transparent: true,
                'opacity': 0.8
            });
        {%  elif resource.ptype == "gxp_arcrestsource" %}
            tile_layer = L.esri.dynamicMapLayer('{{ resource.ows_url|safe }}', {
                layers: '{{ resource.alternate }}',
                format: 'png',
                transparent: true,
                'opacity': 0.8
            });
        {% elif resource.ows_url %}
            tile_layer = L.tileLayer.betterWms('{{ resource.ows_url|safe }}', {
              layers: '{{ resource.alternate }}',
              transparent: true,
              format: 'image/png'
            });
        {% endif %}

        if (tile_layer != null) {
            overlay_layer["{{ resource.title }}"] = tile_layer;
            map.addLayer(tile_layer);
        }
        var layerControl = L.control.layers(
                base_maps, overlay_layer
        ).addTo(map);

        if (L.control.hasOwnProperty('fullscreen')) {
            L.control.fullscreen().addTo(map);
        }

        if(L.Control.hasOwnProperty('opacitySlider')) {
            //adjust opacity
            var opacitySlider = new L.Control.opacitySlider();
            map.addControl(opacitySlider);

            opacitySlider.setOpacityLayer(tile_layer);
        }

        if(L.control.hasOwnProperty('navbar')){
            //adjust info
            L.control.navbar().addTo(map);
        }

        {% if OGC_SERVER.default.BACKEND == 'geonode.qgis_server' %}
            {# expose map object to window #}
            window.preview_map = map;
            window.tile_layer = tile_layer;

            {# Trigger dialog for Style edit #}
            $(".style-edit").on('click', function (event) {
                $("#qgis-server-style-edit").modal('show');
            });

            {# Attach form submit event #}
            $("#qgis-server-style-add-form").on('submit', edit_style_on_submit);

            {# Attach handler for style change #}
            $("input[name='style']").on('change', function(event){
                var $input = $(this);
                if($input.prop('checked') == true){
                    {# Tile url change #}
                    var url;
                    {% if resource.get_tiles_url %}
                        url = '{% url "qgis_server:tile" layername=resource.name style='style_name' %}';
                        url = url.replace('style_name', $input.attr('id'));
                        url = decodeURIComponent(url);
                        tile_layer.setUrl(url);
                    {% endif %}

                    {# Legend icon change #}
                    url = '{% url "qgis_server:legend" layername=resource.name style='style_name' %}';
                    url = url.replace('style_name', $input.attr('id'));
                    url = decodeURIComponent(url);
                    $("#legend_icon").attr('src', url);
                }
            });
        {% endif %}
  });

  function zoom_to_box(map, bbox) {
          var bounds = [
              [bbox[1], bbox[0]],
              [bbox[3], bbox[2]]
          ];
          map.fitBounds(bounds);
      }


  {% if OGC_SERVER.default.BACKEND == 'geonode.qgis_server' %}

    function createMapThumbnail() {
        {# Use map extent #}
        var map = window.preview_map;
        var bbox = map.getBounds().toBBoxString();
        var data = {
            'bbox': bbox
        };
        $.post('{% url "qgis_server:set-thumbnail" layername=resource.name %}', data);
    }

    {# Event handler for style editing #}
    function edit_style_on_submit(event){
        {# prevent form submit by default #}
        var data = new FormData();
        $.each($("#id_qml")[0].files, function(i, file){
            data.append('qml', file);
        });
        data.append('name', $("#id_name").val());
        data.append('title', $("#id_title").val());
        var action = $(this).attr('action');
        $.ajax({
            url: action,
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            type: 'POST',
            success: function(data){
                if(data){
                    $("#qgis-server-style-edit .modal-body").html(data);
                    $(document).ready(function() {
                        $("#qgis-server-style-add-form").on('submit', edit_style_on_submit);
                    });
                }
            },
            error: function(jqXhr, textStatus, errorThrown){
                $("#qgis-server-style-edit .modal-body").html(jqXhr.responseText);
                $(document).ready(function() {
                    $("#qgis-server-style-add-form").on('submit', edit_style_on_submit);
                });
            }
        });
        return false;
    }
  {% endif %}
</script>

{% if OGC_SERVER.default.BACKEND == 'geonode.qgis_server' %}
    <style>
        #qgis-server-style-edit .modal-body{
            overflow-y: scroll;
            max-height: 600px;
        }
    </style>
    <div class="modal fade" id="qgis-server-style-edit" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{% trans "Upload QML Style" %}</h4>
                </div>
                <div class="modal-body">
                    {% include "qgis_server/forms/qml_style.html" %}
                </div>
            </div>
        </div>
    </div>
{% endif %}

geonode/layers/templates/layers/layer_metadata_detail.html
{% extends "metadata_detail.html" %}